# Generated by Django 6.1 on 2026-09-04 08:40

import apps.staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_master_slug_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='avatar',
            field=models.ImageField(upload_to=apps.staff.models.master_avatar_path),
        ),
    ]
