# Generated by Django 6.1 on 2026-09-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='branch',
        ),
    ]
